demo/config/routes.rb
Demo::Application.routes.draw do
  resources :posts

  resources :editors

  resources :galleries

end

demo/app/models/editor.rb
class Editor < ActiveRecord::Base
  attr_accessible :email, :name, :password
end

demo/app/models/gallery.rb
class Gallery < ActiveRecord::Base

 attr_accessible :image, :name
end

demo/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :post, :posted_by
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  # GET /editors
  # GET /editors.json
  def index
    @editors = Editor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @editors }
    end
  end

  # GET /editors/1
  # GET /editors/1.json
  def show
    @editor = Editor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @editor }
    end
  end

  # GET /editors/new
  # GET /editors/new.json
  def new
    @editor = Editor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @editor }
    end
  end

  # GET /editors/1/edit
  def edit
    @editor = Editor.find(params[:id])
  end

  # POST /editors
  # POST /editors.json
  def create
    @editor = Editor.new(params[:editor])

    respond_to do |format|
      if @editor.save
        format.html { redirect_to @editor, notice: 'Editor was successfully created.' }
        format.json { render json: @editor, status: :created, location: @editor }
      else
        format.html { render action: "new" }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /editors/1
  # PUT /editors/1.json
  def update
    @editor = Editor.find(params[:id])

    respond_to do |format|
      if @editor.update_attributes(params[:editor])
        format.html { redirect_to @editor, notice: 'Editor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editors/1
  # DELETE /editors/1.json
  def destroy
    @editor = Editor.find(params[:id])
    @editor.destroy

    respond_to do |format|
      format.html { redirect_to editors_url }
      format.json { head :no_content }
    end
  end
end

demo/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/editors_helper.rb
module EditorsHelper
end

demo/app/helpers/galleries_helper.rb
module GalleriesHelper
end

demo/app/helpers/posts_helper.rb
module PostsHelper
end

demo/app/views/editors/_form.html.erb
<%= form_for(@editor) do |f| %>
  <% if @editor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editor.errors.count, "error") %> prohibited this editor from being saved:</h2>

      <ul>
      <% @editor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/editors/edit.html.erb
<h1>Editing editor</h1>

<%= render 'form' %>

<%= link_to 'Show', @editor %> |
<%= link_to 'Back', editors_path %>

demo/app/views/editors/index.html.erb
<h1>Listing editors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @editors.each do |editor| %>
  <tr>
    <td><%= editor.name %></td>
    <td><%= editor.email %></td>
    <td><%= editor.password %></td>
    <td><%= link_to 'Show', editor %></td>
    <td><%= link_to 'Edit', edit_editor_path(editor) %></td>
    <td><%= link_to 'Destroy', editor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Editor', new_editor_path %>

demo/app/views/editors/new.html.erb
<h1>New editor</h1>

<%= render 'form' %>

<%= link_to 'Back', editors_path %>

demo/app/views/editors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @editor.name %>
</p>

<p>
  <b>Email:</b>
  <%= @editor.email %>
</p>

<p>
  <b>Password:</b>
  <%= @editor.password %>
</p>


<%= link_to 'Edit', edit_editor_path(@editor) %> |
<%= link_to 'Back', editors_path %>

demo/app/views/galleries/_form.html.erb
<%= form_for(@gallery , :html => { :multipart => true }) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

demo/app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.name %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>

demo/app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

demo/app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gallery.name %>
</p>
<% if @gallery.image? %>
	<%= image_tag @project.image.url %>
	<br />
	<%= link_to @project.image.url, @project.image.url%>
	%>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

demo/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :posted_by %><br />
    <%= f.text_field :posted_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

demo/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Posted by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.post %></td>
    <td><%= post.posted_by %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Delete', 'posts', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

demo/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

demo/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @post.post %>
</p>

<p>
  <b>Posted by:</b>
  <%= @post.posted_by %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>